<?php 
/*
Plugin Name: CalEnvios
Plugin URI: https://github.com/Yoseph-Reyes/plugWP-CalEnv
Description: Plugin de WordPress para calcular el costo de un envio en Woocommerce a cualquier direccion
Version: 0.1
Author: Yoseph Reyes
Author URI: https://github.com/Yoseph-Reyes
Text Domain: cenv
Generated By: http://ensuredomains.com
License: Pendiente puede ser MIT
*/

defined('ABSPATH') or die("Bye bye");

define('cenvRuta',plugin_dir_path(__FILE__));

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}


function cenvtextsender( $checkout ) { //FUNCION PARA AÑADIR EL FORMULARIO
 
    echo '<div id="additional_checkout_field"><h2>' . __('Información para envios') . '</h2>';
    
    //INPUT DIRECCION
    woocommerce_form_field( 'dirr', array(
        'type'          => 'text',
        'class'         => array('my-field-class form-row-wide'),
        'label'         => __('Street Adress'),
        'placeholder'   => __('Example'),
        ), $checkout->get_value( 'dirr' ));
    
        //INPUT ESTADO
    woocommerce_form_field( 'state', array(
        'type'          => 'state',
        'class'         => array('my-field-class form-row-wide'),
        'label'         => __('State'),        
        ), $checkout->get_value( 'state' ));

    //INPUT PAIS
    woocommerce_form_field( 'country', array(
        'type'          => 'contry',
        'class'         => array('my-field-class form-row-wide'),
        'label'         => __('State'),        
        ), $checkout->get_value( 'country' ));
        
        //INPUT CODIGO POSTAL
    woocommerce_form_field( 'zip', array(
        'type'          => 'text',
        'class'         => array('my-field-class form-row-wide'),
        'label'         => __('Postal Code'),
        'placeholder'   => __('20202'),
        ), $checkout->get_value( 'zip' ));    
        
        echo '</div>';
    }
    add_action( 'woocommerce_after_order_notes',cenvtextsender());